version: '3.9'

services:
  sig-provider:
    image: ghcr.io/blockscout/sig-provider:${SIG_PROVIDER_DOCKER_TAG:-v1.0.0}
    pull_policy: always
    platform: linux/amd64
    restart: always
    container_name: 'sig-provider'
