# renew_before_expiry = 30 days
version = 4.0.0
archive_dir = /etc/letsencrypt/archive/testnet.langitchain.xyz
cert = /etc/letsencrypt/live/testnet.langitchain.xyz/cert.pem
privkey = /etc/letsencrypt/live/testnet.langitchain.xyz/privkey.pem
chain = /etc/letsencrypt/live/testnet.langitchain.xyz/chain.pem
fullchain = /etc/letsencrypt/live/testnet.langitchain.xyz/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = 89d097f55416c5f7a6c4a18ca09ed548
authenticator = standalone
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
